version: 0.1

path:
  home: # use custom path when needed
  desktop: /usr/share/applications
  bin: /usr/bin

vim:
  dir: .vim
  config: .vimrc
  gtk: .gtkrc-2.0-vim
  tmp: [swap, backup]

gvim:
  script: gvim_for_rails
  desktop: gvim_for_rails.desktop

greeting: |
  ====================
  Rails Bundle for Vim
  ====================

  Ruby on Rails development environment inside Vim.
  Contribute to https://github.com/smolnar/vim-rails-bundle for everlasting fame and all the women!
  --------------------
